language: node_js
node_js:
  - node
  - 12
  - 10

cache:
  yarn: true
  directories:
    - .eslintcache

install:
  - yarn install
script:
  - yarn run build
  - yarn run lint --cache
  - yarn test --coverage
after_success:
  - codecov

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
