language: node_js
node_js:
  - node
  - 10
  - 8

cache:
  yarn: true
  directories:
    - .eslintcache

install:
  - yarn install
script:
  - yarn run lint --cache --cache-location ".eslintcache/"
  - yarn test --coverage
after_success:
  - codecov

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
